name: Build for Raspberry Pico

on:
  push:
    paths:
      - "embedded/**"
      - ".github/workflows/build-pico.yml"
  pull_request:
    paths:
      - "embedded/**"
      - ".github/workflows/build-pico.yml"

jobs:
  test_build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake \
            gcc-arm-none-eabi \
            binutils-arm-none-eabi \
            libnewlib-arm-none-eabi \
            libstdc++-arm-none-eabi-newlib \
            make

      - name: Run CMake
        run: cmake -S ${{ github.workspace }}/embedded/src -B ${{ github.workspace }}/build
        env:
          # если pico-sdk лежит в корне репо
          PICO_SDK_PATH: ${{ github.workspace }}/pico-sdk

      - name: Compile
        run: |
          cd build
          make humidity-sensor

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: humidity-sensor-${{ github.sha }}
          path: |
            build/*.elf
            build/*.uf2
            build/*.map
