name: Lint & Build for Raspberry Pico

on: [push, pull_request]

jobs:
  test_build:
    name: Lint & Build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get build tools
        run: sudo apt-get update && sudo apt-get install -y cmake gcc-arm-none-eabi libnewlib-arm-none-eabi libstdc++-arm-none-eabi-newlib

      - name: Run CMake
        run: cmake -S ${{github.workspace}}/src -B ${{github.workspace}}/build

      - name: Compile
        working-directory: ${{github.workspace}}/build
        run: make humidity-sensor
        id: build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: humidity-sensor-pico-files
          path: |
            .build/*.elf
            .build/*.uf2
            .build/*.elf.map
