name: Lint + Build for Raspberry Pico

on:
  push:
    paths:
      - "embedded/**"
      - ".github/workflows/lint-build-pico.yml.bak"
  pull_request:
    paths:
      - "embedded/**"
      - ".github/workflows/lint-build-pico.yml.bak"

jobs:
  test_build:
    name: Lint + Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake \
            gcc-arm-none-eabi \
            binutils-arm-none-eabi \
            libnewlib-arm-none-eabi \
            libstdc++-arm-none-eabi-newlib \
            make

      - name: Run CMake
        run: cmake -S ${{ github.workspace }}/embedded/src -B ${{ github.workspace }}/build
        env:
          # pico-sdk лежит в корне репозитория
          PICO_SDK_PATH: ${{ github.workspace }}/pico-sdk

      # "Lint" = сборка с warning’ами (как и было раньше)
      - name: Compile
        working-directory: ${{ github.workspace }}/build
        run: make humidity-sensor
        id: build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: humidity-sensor-${{ github.sha }}
          path: |
            build/*.elf
            build/*.uf2
            build/*.map
            build/*.elf.map
